declare module "vitest" {
  export function describe(name: string, fn: () => void): void;
  export function it(name: string, fn: () => void | Promise<void>): void;
  export function expect(value: unknown): {
    toBe(value: unknown): void;
    toEqual(value: unknown): void;
    toBeTruthy(): void;
    toBeFalsy(): void;
    toBeNull(): void;
    toBeUndefined(): void;
    toContain(value: unknown): void;
    toHaveLength(length: number): void;
    toThrow(message?: string | RegExp): void;
    toThrowError(message?: string | RegExp): void;
    toMatch(matcher: string | RegExp): void;
    toBeGreaterThan(value: number): void;
    toBeLessThan(value: number): void;
    toBeGreaterThanOrEqual(value: number): void;
    toBeLessThanOrEqual(value: number): void;
    toBeCloseTo(value: number, numDigits?: number): void;
    toBeDefined(): void;
    toBeInstanceOf<T>(constructor: new (...args: unknown[]) => T): void;
    toHaveProperty(path: string | string[], value?: unknown): void;
    toMatchObject(obj: Record<string, unknown>): void;
    toMatchInlineSnapshot(snapshot?: string): void;
    toMatchSnapshot(snapshot?: string): void;
    toStrictEqual(value: unknown): void;
    toBeNaN(): void;
    toBeFinite(): void;
    toBePositive(): void;
    toBeNegative(): void;
    toBeEven(): void;
    toBeOdd(): void;
    toInclude(): void;
    toSatisfy(predicate: (value: unknown) => boolean): void;
    toHaveBeenCalled(): void;
    toHaveBeenCalledTimes(times: number): void;
    toHaveBeenCalledWith(...args: unknown[]): void;
    toHaveBeenCalledExpectations(): void;
    toHaveReturned(): void;
    toHaveReturnedTimes(times: number): void;
    toHaveReturnedWith(value: unknown): void;
    toHaveLastReturnedWith(value: unknown): void;
    toHaveNthReturnedWith(nth: number, value: unknown): void;
    toThrowErrorMatchingSnapshot(snapshot?: string): void;
    toThrowErrorMatchingInlineSnapshot(snapshot?: string): void;
    resolves: {
      toBe(value: unknown): Promise<void>;
      toEqual(value: unknown): Promise<void>;
      toBeTruthy(): Promise<void>;
      toBeFalsy(): Promise<void>;
      toBeNull(): Promise<void>;
      toBeUndefined(): Promise<void>;
      toContain(value: unknown): Promise<void>;
      toHaveLength(length: number): Promise<void>;
      toThrow(): Promise<void>;
      toThrowError(message?: string | RegExp): Promise<void>;
      toMatch(matcher: string | RegExp): Promise<void>;
      toBeCloseTo(value: number, numDigits?: number): Promise<void>;
      toBeDefined(): Promise<void>;
      toBeInstanceOf<T>(constructor: new (...args: unknown[]) => T): Promise<void>;
      toHaveProperty(path: string | string[], value?: unknown): Promise<void>;
      toMatchObject(obj: Record<string, unknown>): Promise<void>;
      toMatchInlineSnapshot(snapshot?: string): Promise<void>;
      toMatchSnapshot(snapshot?: string): Promise<void>;
      toStrictEqual(value: unknown): Promise<void>;
      toBeNaN(): Promise<void>;
      toBeFinite(): Promise<void>;
      toBePositive(): Promise<void>;
      toBeNegative(): Promise<void>;
      toBeEven(): Promise<void>;
      toBeOdd(): Promise<void>;
      toInclude(): Promise<void>;
      toSatisfy(predicate: (value: unknown) => boolean): Promise<void>;
    };
    rejects: {
      toBe(value: unknown): Promise<void>;
      toEqual(value: unknown): Promise<void>;
      toBeTruthy(): Promise<void>;
      toBeFalsy(): Promise<void>;
      toBeNull(): Promise<void>;
      toBeUndefined(): Promise<void>;
      toContain(value: unknown): Promise<void>;
      toHaveLength(length: number): Promise<void>;
      toThrow(): Promise<void>;
      toThrowError(message?: string | RegExp): Promise<void>;
      toMatch(matcher: string | RegExp): Promise<void>;
      toBeCloseTo(value: number, numDigits?: number): Promise<void>;
      toBeDefined(): Promise<void>;
      toBeInstanceOf<T>(constructor: new (...args: unknown[]) => T): Promise<void>;
      toHaveProperty(path: string | string[], value?: unknown): Promise<void>;
      toMatchObject(obj: Record<string, unknown>): Promise<void>;
      toMatchInlineSnapshot(snapshot?: string): Promise<void>;
      toMatchSnapshot(snapshot?: string): Promise<void>;
      toStrictEqual(value: unknown): Promise<void>;
      toBeNaN(): Promise<void>;
      toBeFinite(): Promise<void>;
      toBePositive(): Promise<void>;
      toBeNegative(): Promise<void>;
      toBeEven(): Promise<void>;
      toBeOdd(): Promise<void>;
      toInclude(): Promise<void>;
      toSatisfy(predicate: (value: unknown) => boolean): Promise<void>;
    };
    not: {
      toBe(value: unknown): void;
      toEqual(value: unknown): void;
      toBeTruthy(): void;
      toBeFalsy(): void;
      toBeNull(): void;
      toBeUndefined(): void;
      toContain(value: unknown): void;
      toHaveLength(length: number): void;
      toThrow(): void;
      toThrowError(message?: string | RegExp): void;
      toMatch(matcher: string | RegExp): void;
      toBeCloseTo(value: number, numDigits?: number): void;
      toBeDefined(): void;
      toBeInstanceOf<T>(constructor: new (...args: unknown[]) => T): void;
      toHaveProperty(path: string | string[], value?: unknown): void;
      toMatchObject(obj: Record<string, unknown>): void;
      toMatchInlineSnapshot(snapshot?: string): void;
      toMatchSnapshot(snapshot?: string): void;
      toStrictEqual(value: unknown): void;
      toBeNaN(): void;
      toBeFinite(): void;
      toBePositive(): void;
      toBeNegative(): void;
      toBeEven(): void;
      toBeOdd(): void;
      toInclude(): void;
      toSatisfy(predicate: (value: unknown) => boolean): void;
    };
  };
}
